# Taken from OVOMONO ci/dev/golangci.yml
# You must update the lint with the one from OVOMONO repo.
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gosec
    - misspell
    - nakedret
    - nestif
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - unconvert
    - unparam
    - wsl

run:
  skip-dirs:
    - ".*/mocks/.*"
    - ".*/lua/.*"
    - ".*/thrift/.*"
    - ".*/pb/.*"
    - ".*/resources/.*"
    - ".*/cmd/.*"

  skip-files:
    - "mock_.*\\.go$"
    - ".*\\.pb\\.go$"
    - "z_.*\\.go$"

  skip-dirs-use-default: true

  modules-download-mode: readonly

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m

issues:
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    - path: "(.+)_test.go"
      linters:
        - bodyclose
        - dupl
        - errcheck
        - funlen
        - goconst
        - lll
        - noctx
        - gosec

    - path: "doc.go"
      linters:
        - gochecknoinits

    - text: "block should not start with a whitespace"
      linters:
        - wsl

    - text: "Top level comment should end in a period"
      linters:
        - godot

    - text: "G107: Potential HTTP request made with variable url"
      path: "(.+)_test.go"
      linters:
        - gosec

linters-settings:
  depguard:
    list-type: blacklist
    packages:

  dupl:
    threshold: 100

  errcheck:
    check-type-assertions: true

  exhaustive:
    # indicates that switch statements are to be considered exhaustive if a 'default' case is present
    default-signifies-exhaustive: true

  funlen:
    lines: 42
    statements: 50

  gocognit:
    min-complexity: 20

  gocritic:
    enabled-tags:
      - performance
      - style
      - opinionated
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - whyNoLint

  gocyclo:
    min-complexity: 15

  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return

  govet:
    check-shadowing: true

  maligned:
    suggest-new: true

  misspell:
    locale: US

  wsl:
    allow-cuddle-declarations: true
    allow-trailing-comment: true
    allow-case-trailing-whitespace: true
    force-case-trailing-whitespace: 1
    enforce-error-cuddling: true
