linters:
  disable-all: true
  enable:
    - gofumpt
    - goimports

linters-settings:
  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    # Default: ""
    local-prefixes: gitlab.com/ovoeng

run:
  skip-dirs:
    - ".*/mocks/.*"
    - ".*/lua/.*"
    - ".*/thrift/.*"
    - ".*/idl/.*"
    - ".*/resources/.*"
    - ".*/cmd/.*"
    - ".*/testdata/.*"
    - ".*/mockdata/.*"

  # Enables skipping of directories:
  # - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  # Default: true
  skip-dirs-use-default: true

  skip-files:
    - "mock_.*\\.go$"
    - ".*\\.pb\\.go$"
    - "z_.*\\.go$" # any file with prefix `z_` it is a custom generated code

  modules-download-mode: vendor

  # Include test files or not.
  # Default: true
  tests: true

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 20m

  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: true

issues:
  gofumpt:
    extra-rules: true

  # Auto-fix things where possible
  fix: true
